version: '3'
services:
  app:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/library?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=0000
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=library
    volumes:
      - ./library.sql:/docker-entrypoint-initdb.d/library.sql
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: