name: Manual Jar Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag name (e.g., v1.0.0)'
        required: true

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload jar to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/*.jar
        tag_name: ${{ github.event.inputs.tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
